"""expand event normalization schema

Revision ID: 08353c313728
Revises: c36058928e24
Create Date: 2026-06-06 17:56:38.261942

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08353c313728"
down_revision: Union[str, Sequence[str], None] = "c36058928e24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("source_event_id", sa.String(), nullable=False))
    op.add_column("events", sa.Column("severity_hint", sa.String(), nullable=True))
    op.add_column("events", sa.Column("urgency_hint", sa.String(), nullable=True))
    op.add_column("events", sa.Column("certainty_hint", sa.String(), nullable=True))
    op.add_column("events", sa.Column("geometry_geojson", sa.JSON(), nullable=True))
    op.create_unique_constraint(
        "uq_source_event",
        "events",
        ["source_id", "source_event_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_source_event", "events", type_="unique")
    op.drop_column("events", "geometry_geojson")
    op.drop_column("events", "certainty_hint")
    op.drop_column("events", "urgency_hint")
    op.drop_column("events", "severity_hint")
    op.drop_column("events", "source_event_id")
    # ### end Alembic commands ###
