"""expand event normalization schema

Revision ID: 9af28a066d25
Revises: 08353c313728
Create Date: 2026-06-06 18:02:25.293549

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9af28a066d25"
down_revision: Union[str, Sequence[str], None] = "08353c313728"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
